name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux deps
        run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo cache (common)
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cargo-common-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
      - name: Cargo cache (debug)
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
